alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: bundlelines-staging.bundle.app
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: bundle-lines
    match:
      path:
        prefix: /
name: bundlelines-staging
region: fra
services:
- envs:
  - key: AUTH_ORIGIN
    scope: RUN_AND_BUILD_TIME
    value: https://bundlelines-staging.bundle.app
  http_port: 8080
  image:
    deploy_on_push: {}
    registry_type: DOCR
    repository: bundle-lines
    tag: staging
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: bundle-lines
